"""user_stats

Revision ID: 581fdb99a8bb
Revises: 19c0846f6344
Create Date: 2017-03-23 16:43:21.707554

"""

# revision identifiers, used by Alembic.
revision = '581fdb99a8bb'
down_revision = '19c0846f6344'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from datetime import datetime

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_spwaner_start', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('total_time', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE users set last_spwaner_start = '{0}', total_time = 0".format(datetime.utcnow()))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_time')
    op.drop_column('users', 'last_spwaner_start')
    # ### end Alembic commands ###
